# Generated by Django 5.2.8 on 2026-02-20 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Category', models.CharField(choices=[('Roads & Infrastructure', 'Roads & Infrastructure'), ('Water Supply', 'Water Supply'), ('Sanitation', 'Sanitation'), ('Street Lighting', 'Street Lighting'), ('Drainage', 'Drainage'), ('Illegal Construction', 'Illegal Construction'), ('Noise Pollution', 'Noise Pollution'), ('Other', 'Other')], default='Other')),
                ('Description', models.CharField(max_length=300)),
                ('image_video', models.FileField(blank=True, null=True, upload_to='media/')),
                ('location_address', models.CharField(max_length=200)),
                ('location_District', models.CharField(max_length=100)),
                ('location_taluk', models.CharField(max_length=100)),
                ('priority_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], default='open')),
                ('current_time', models.DateTimeField(default=datetime.datetime(2026, 2, 20, 23, 47, 42, 52976))),
            ],
        ),
    ]
