# Generated by Django 5.2.8 on 2026-02-20 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 0, 44, 0, 143325)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], default='open'),
        ),
    ]
