# Generated by Django 5.2.8 on 2026-02-20 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_current_time_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 0, 45, 11, 464669)),
        ),
    ]
