# Generated by Django 5.2.8 on 2026-02-21 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 18, 11, 54, 477410)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('in-progress', 'In Progress'), ('resolved', 'resolved')], default='open'),
        ),
    ]
