# Generated by Django 5.2.8 on 2026-02-21 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_current_time_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 18, 13, 0, 196518)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], default='open'),
        ),
    ]
