# Generated by Django 5.2.8 on 2026-02-21 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_alter_complaint_current_time_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Category',
            field=models.CharField(choices=[('Roads & Infrastructure', 'Roads & Infrastructure'), ('Water Supply', 'Water Supply'), ('Sanitation', 'Sanitation'), ('Street Lighting', 'Street Lighting'), ('Drainage', 'Drainage'), ('Illegal Construction', 'Illegal Construction'), ('Noise Pollution', 'Noise Pollution'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='current_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
