# Generated by Django 5.2.8 on 2026-02-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_alter_complaint_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Category',
            field=models.CharField(choices=[('ROADS', 'Roads & Infrastructure'), ('TRAFFIC', 'Traffic & Road Safety'), ('WATER', 'Water Supply'), ('SEWERAGE', 'Sewerage & Drainage'), ('SANITATION', 'Sanitation & Garbage'), ('LIGHTING', 'Street Lighting'), ('PARKS', 'Parks & Public Spaces'), ('ANIMALS', 'Stray Animals'), ('ILLEGAL_CONSTRUCTION', 'Illegal Construction'), ('ENCROACHMENT', 'Encroachment'), ('PROPERTY_DAMAGE', 'Public Property Damage'), ('ELECTRICITY', 'Electricity & Power Issues'), ('OTHER', 'Other')], default='Other', max_length=50),
        ),
    ]
