# Generated by Django 5.2.8 on 2026-02-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_complaint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='officer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
