# Generated by Django 5.2.8 on 2026-02-25 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_remove_complaint_officer_name_complaint_officer_id'),
        ('departments', '0005_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='complaints.complaint')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_assignments', to='departments.officer')),
            ],
            options={
                'unique_together': {('complaint', 'officer')},
            },
        ),
    ]
