# Generated by Django 5.2.8 on 2026-03-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_alter_complaintassignment_complaint_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='comp_id',
        ),
        migrations.AddField(
            model_name='complaint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
