# Generated by Django 5.2.8 on 2026-03-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0017_alter_complaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintassignment',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20),
        ),
    ]
