# Generated by Django 5.2.8 on 2026-03-17 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0003_alter_category_code'),
        ('complaints', '0018_alter_complaintassignment_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='Categories.category'),
        ),
    ]
