# Generated by Django 5.2.8 on 2026-03-17 04:57

from django.db import migrations, models
import django.db.models.deletion


def fix_category_references(apps, schema_editor):
    Complaint = apps.get_model('complaints', 'Complaint')
    Category = apps.get_model('Categories', 'Category')
    
    # Get valid category IDs from Categories table
    valid_category_ids = set(Category.objects.values_list('id', flat=True))
    
    # Update complaints with invalid category references to NULL
    Complaint.objects.exclude(Category_id__in=valid_category_ids).update(Category_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0019_alter_complaint_category'),
        ('Categories', '0001_initial'),
    ]

    operations = [
        # First fix data
        migrations.RunPython(fix_category_references, migrations.RunPython.noop),
        
        # Then alter the field
        migrations.AlterField(
            model_name='complaint',
            name='Category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='complaints',
                to='Categories.category',
            ),
        ),
    ]
