# Generated by Django 5.2.8 on 2026-03-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0023_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
