# Generated by Django 5.2.8 on 2026-02-25 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaint_officer_name'),
        ('departments', '0005_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='officer_name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='officer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='departments.officer'),
        ),
    ]
