# Generated by Django 5.2.8 on 2026-03-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_remove_complaint_comp_id_complaint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_assignd',
            field=models.BooleanField(default=False),
        ),
    ]
