# Generated by Django 5.2.8 on 2026-03-15 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_convert_category_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='complaints.complaintcategory'),
        ),
    ]
